language: python
python:
  - "3.6"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install iminuit==1.5.4   # Iminuit 2 introduced breaking changes
  - pip install coveralls
  - python setup.py install
script:
  - coverage run --source=blueice setup.py test
after_success:
- coveralls
