language: python
python:
  - 3.4
notifications:
  email: false

sudo: false

addons:
  apt:
    packages:
     - gdb
     - apport

before_install:
  # What is the current file size max for core files?
  # It is usually 0, which means no core file will be dumped if there is a crash
  - ulimit -c
  - ulimit -a -S
  - ulimit -a -H
  # Setup Miniconda - a lightweight anaconda
  # This allows us to get pre-build binaries from numpy etc. from binstar
  # This is quicker and more reliable than compiling from source every build
  # See  https://gist.githubusercontent.com/dan-blanchard/7045057/raw/8ca5a4abcd0c65ab05217dd92119001f8454c369/.travis.yml
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes conda

install:
  # Set the core file limit to unlimited so a core file is generated upon crash
  - ulimit -c unlimited -S
  - ulimit -c
  - ulimit -a -S
  - ulimit -a -H
  - cat /proc/sys/kernel/core_pattern
  # Download numpy and matplotlib binaries from binstar
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy pandas
  - conda install -c astropy iminuit
  # Setup coverage for converage measurement
  - pip install coverage
  - pip install coveralls
  - python setup.py install


before_script:
  - RESULT=0


script:
  # Run the program to prompt a crash
  # Note: we capture the return code of the program here and add
  # `|| true` to ensure that travis continues past the crash
  # Run tests
  - coverage run --source=blueice setup.py test || RESULT=$?
  - ls -l
  - if [[ ${RESULT} == 0 ]]; then echo "\\o/ our test worked without problems"; else echo "ruhroh test returned an errorcode of $RESULT"; fi;
  # If the program returned an error code, now we check for a
  # core file in the current working directory and dump the backtrace out
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb python core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
  # now we should present travis with the original
  # error code so the run cleanly stops
  - if [[ ${RESULT} != 0 ]]; then exit $RESULT ; fi;


after_success:
  # Calculate coverage
  - coveralls
