language: python
python:
  - "3.4"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install iminuit
  - pip install coveralls
  - python setup.py install
script:
  - coverage run --source=blueice setup.py test
after_success:
- coveralls
